# Generated by Django 2.1.7 on 2019-05-04 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='total',
            new_name='total_price',
        ),
    ]
