# Generated by Django 2.1.7 on 2019-05-06 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='item_number',
            field=models.IntegerField(default=-1),
        ),
    ]
